version: '3.8'

services:
  catalog.api:
    container_name: lde.catalog.api.candyshop
    build:
      context: .
      dockerfile: Catalog/Catalog.Host/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionString=server=www.candywebshop.com;port=5433;database=catalog;uid=postgres;password=postgres;
      - PathBase=http://www.candywebshop.com:5000
    depends_on:
      - postgres
    ports:
      - 5000:5000
  nginx:
    image: nginx
    container_name: lde.nginx.candyshop
    ports:
      - 80:80
    volumes:
      - ./Proxy/gateway/nginx/conf.d:/etc/nginx/conf.d
      - ./Proxy/assets:/var/www/assets
  postgres:
    image: postgres
    container_name: lde.postgres.candyshop
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
networks:
  default:
    driver: bridge
    internal: false
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1